### ISSUE TITLE
org.jnode.assembler.x86.InvalidOpcodeException during build

### ISSUE THREAD

**Issue by janseeger** [jnode/jnode#38]
```
java-image:
[bootimage] JNode native compiler defaulting to 'L1A'
[bootimage] Building for CPUID
[bootimage]  name     : GenuineIntel
[bootimage]  brand    : ?
[bootimage]  family   : 0
[bootimage]  model    : 0
[bootimage]  step     : 0
[bootimage]  features : FPU,PSE
[bootimage]  raw      : 00000001 756E6547 6C65746E 49656E69 00000000 00000000 00000000 00000009
[bootimage] Compiling native kernel with JNAsm, Version 0.2.9-dev, 64 bits
[bootimage] org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:775)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:495)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:871)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
[bootimage]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bootimage]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bootimage]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bootimage]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
[bootimage] Caused by: org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3404)
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3389)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emitMOV(X86Core.java:969)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emit(X86Core.java:294)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.emit(X86Support.java:144)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:110)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:67)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:144)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:119)
[bootimage]     at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:765)
[bootimage]     ... 44 more
[bootimage] --- Nested Exception ---
[bootimage] org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3404)
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3389)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emitMOV(X86Core.java:969)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emit(X86Core.java:294)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.emit(X86Support.java:144)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:110)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:67)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:144)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:119)
[bootimage]     at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:765)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:495)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:871)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
[bootimage]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bootimage]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bootimage]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bootimage]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
[bootimage] org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:666)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:871)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
[bootimage]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bootimage]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bootimage]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bootimage]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
[bootimage] Caused by: org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:775)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:495)
[bootimage]     ... 43 more
[bootimage] Caused by: org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3404)
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3389)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emitMOV(X86Core.java:969)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emit(X86Core.java:294)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.emit(X86Support.java:144)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:110)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:67)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:144)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:119)
[bootimage]     at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:765)
[bootimage]     ... 44 more
[bootimage] --- Nested Exception ---
[bootimage] org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:775)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:495)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:871)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
[bootimage]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bootimage]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bootimage]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bootimage]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
[bootimage] Caused by: org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3404)
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3389)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emitMOV(X86Core.java:969)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emit(X86Core.java:294)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.emit(X86Support.java:144)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:110)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:67)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:144)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:119)
[bootimage]     at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:765)
[bootimage]     ... 44 more
[bootimage] --- Nested Exception ---
[bootimage] org.jnode.assembler.x86.InvalidOpcodeException
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3404)
[bootimage]     at org.jnode.assembler.x86.X86BinaryAssembler.writeMOV_Const(X86BinaryAssembler.java:3389)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emitMOV(X86Core.java:969)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Core.emit(X86Core.java:294)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.emit(X86Support.java:144)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:110)
[bootimage]     at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:67)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:144)
[bootimage]     at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:119)
[bootimage]     at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage]     at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:765)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:495)
[bootimage]     at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:871)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
[bootimage]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
[bootimage]     at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[bootimage]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[bootimage]     at java.lang.reflect.Method.invoke(Method.java:606)
[bootimage]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[bootimage]     at org.apache.tools.ant.Task.perform(Task.java:348)
[bootimage]     at org.apache.tools.ant.Target.execute(Target.java:357)
[bootimage]     at org.apache.tools.ant.Target.performTasks(Target.java:385)
[bootimage]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
[bootimage]     at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
[bootimage]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[bootimage]     at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
[bootimage]     at org.apache.tools.ant.Main.runBuild(Main.java:758)
[bootimage]     at org.apache.tools.ant.Main.startAnt(Main.java:217)
[bootimage]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
[bootimage]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)

BUILD FAILED
/home/jan/dev/jnode/all/build.xml:530: The following error occurred while executing this line:
/home/jan/dev/jnode/all/build.xml:519: The following error occurred while executing this line:
/home/jan/dev/jnode/all/build-x86.xml:215: org.jnode.assembler.x86.InvalidOpcodeException
```

**Comment by LSantha** [comment]
Can you describe the environment (OS, Java) where you get the error?
I've set up travis-ci for building JNode. You may want to compare your environment to it:
https://travis-ci.org/jnode/jnode

**Comment by janseeger** [comment]
```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q8200  @ 2.33GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2003.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dtherm
bogomips	: 4667.94
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

```
$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Comment by IvoClarysse** [comment]
For me, on OS X Yosemite 10.10.2, I get the same org.jnode.assembler.x86.InvalidOpcodeException, when trying to build the cd-x86_64-lite target.

However, building the cd-x86-lite target (like the travis-ci build) works fine.


    $ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by neoedmund** [comment]
Here I have the same problem.
I look into the code:

builder/src/builder/org/jnode/jnasm/assembler/Assembler.java
```
assemble((int) asm.getBaseAddr());
```
This will call 
```
builder/src/builder/org/jnode/jnasm/assembler/x86/X86Support.java
@@ -60,6 +60,7 @@ public class X86Support extends HardwareSupport {
     }
 
     public void assemble(int baseAddress) {
         X86CpuID cpuId = X86CpuID.createID("pentium");
         nativeStream = new X86BinaryAssembler(cpuId, X86Constants.Mode.CODE32, baseAddress);
         ((X86BinaryAssembler) nativeStream).setByteValueEnabled(true);
```
which will force 32bit mode what cause the exception later.


I tried to change 
assemble((int) asm.getBaseAddr());
to 
assemble(asm);

but get another exception:
```

[bootimage] java.lang.IllegalArgumentException: Label already defined: __jnasm_macro_local_label_9
[bootimage] 	at org.jnode.jnasm.assembler.x86.X86Support.doAssembly(X86Support.java:100)
[bootimage] 	at org.jnode.jnasm.assembler.x86.X86Support.assemble(X86Support.java:78)
[bootimage] 	at org.jnode.jnasm.assembler.Assembler.assemble(Assembler.java:149)
[bootimage] 	at org.jnode.jnasm.assembler.Assembler.performTwoPasses(Assembler.java:120)
[bootimage] 	at org.jnode.jnasm.JNAsm.assembler(JNAsm.java:68)
[bootimage] 	at org.jnode.build.x86.BootImageBuilder.compileKernel(BootImageBuilder.java:726)
[bootimage] 	at org.jnode.build.AbstractBootImageBuilder.doExecute(AbstractBootImageBuilder.java:483)
[bootimage] 	at org.jnode.build.AbstractBootImageBuilder.execute(AbstractBootImageBuilder.java:844)
...
```
I don't know who to dig deeper.
